/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 36;
=======
const int buildversion = 9;
>>>>>>> 94767025a17de2ce5cd08c51f110fb555a7b5ef3
const char buildconfig[] = "TEST1";
